[workspace]
authors = ["Tyler Sutterley <tsutterl@uw.edu>"]
channels = ["conda-forge"]
name = "IS2-calval"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
future = "*"
h5py = "*"
lxml = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
pyproj = "*"
python-dateutil = "*"
scikit-learn = "*"
scipy = "*"
timescale = "*"

[pypi-dependencies]
icesat2-toolkit = "*"
